sonar.projectKey=RaceSync-F1
sonar.projectName=RaceSync F1
sonar.projectVersion=1.0
sonar.sources=client,gateway,sector-node
sonar.sourceEncoding=UTF-8
sonar.exclusions=client/public/**,**/node_modules/**,**/.git/**,**/coverage/**,**/.scannerwork/**,**/dist/**,**/build/**,**/*.min.js